server:

  port: 9999



spring:

  application:

    name: zuul-gateway


zuul:

  prefix: /heart

  ignored-services: "*"

  routes:

    mydept.serviceId: lb-test-dept

    mydept.path: /lovel/**

eureka:

  client:

    service-url:

      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka

  instance:

    instance-id: gateway-9527.com

    prefer-ip-address: true

info:

  app.name: heart-lbtest

  company.name: heart.lovel.com

  build.artifactId: $project.artifactId$

  build.version: $project.version$